# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer2.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_options = QtWidgets.QVBoxLayout()
        self.verticalLayout_options.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_options.setSpacing(6)
        self.verticalLayout_options.setObjectName("verticalLayout_options")
        self.comboBox_system_info = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_system_info.setObjectName("comboBox_system_info")
        self.verticalLayout_options.addWidget(self.comboBox_system_info)
        self.button_cpu_views = QtWidgets.QPushButton(self.centralwidget)
        self.button_cpu_views.setAutoDefault(False)
        self.button_cpu_views.setObjectName("button_cpu_views")
        self.verticalLayout_options.addWidget(self.button_cpu_views)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_options.addWidget(self.pushButton)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_options.addWidget(self.textEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_options)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_cpu_perc_plots = QtWidgets.QWidget()
        self.tab_cpu_perc_plots.setObjectName("tab_cpu_perc_plots")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_cpu_perc_plots)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_cpu_plots = QtWidgets.QVBoxLayout()
        self.verticalLayout_cpu_plots.setObjectName("verticalLayout_cpu_plots")
        self.verticalLayout_3.addLayout(self.verticalLayout_cpu_plots)
        self.tabWidget.addTab(self.tab_cpu_perc_plots, "")
        self.tab_cpu_per_bars = QtWidgets.QWidget()
        self.tab_cpu_per_bars.setObjectName("tab_cpu_per_bars")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_cpu_per_bars)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_cpu_progress_bars = QtWidgets.QVBoxLayout()
        self.verticalLayout_cpu_progress_bars.setObjectName("verticalLayout_cpu_progress_bars")
        self.verticalLayout_2.addLayout(self.verticalLayout_cpu_progress_bars)
        self.tabWidget.addTab(self.tab_cpu_per_bars, "")
        self.tab_extra_info = QtWidgets.QWidget()
        self.tab_extra_info.setObjectName("tab_extra_info")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_extra_info)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_cpu_extra_info = QtWidgets.QVBoxLayout()
        self.verticalLayout_cpu_extra_info.setObjectName("verticalLayout_cpu_extra_info")
        self.verticalLayout_4.addLayout(self.verticalLayout_cpu_extra_info)
        self.tabWidget.addTab(self.tab_extra_info, "")
        self.tab_memory_info = QtWidgets.QWidget()
        self.tab_memory_info.setObjectName("tab_memory_info")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_memory_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_memory_info = QtWidgets.QVBoxLayout()
        self.verticalLayout_memory_info.setObjectName("verticalLayout_memory_info")
        self.verticalLayout.addLayout(self.verticalLayout_memory_info)
        self.tabWidget.addTab(self.tab_memory_info, "")
        self.tab_net_info = QtWidgets.QWidget()
        self.tab_net_info.setObjectName("tab_net_info")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_net_info)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_network_info = QtWidgets.QVBoxLayout()
        self.verticalLayout_network_info.setObjectName("verticalLayout_network_info")
        self.verticalLayout_5.addLayout(self.verticalLayout_network_info)
        self.tabWidget.addTab(self.tab_net_info, "")
        self.tab_proc_info = QtWidgets.QWidget()
        self.tab_proc_info.setObjectName("tab_proc_info")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_proc_info)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_processes_info = QtWidgets.QVBoxLayout()
        self.verticalLayout_processes_info.setObjectName("verticalLayout_processes_info")
        self.verticalLayout_6.addLayout(self.verticalLayout_processes_info)
        self.tabWidget.addTab(self.tab_proc_info, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1091, 20))
        self.menuBar.setObjectName("menuBar")
        self.menufile = QtWidgets.QMenu(self.menuBar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionFIl = QtWidgets.QAction(MainWindow)
        self.actionFIl.setObjectName("actionFIl")
        self.menufile.addSeparator()
        self.menuBar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPU Monitor"))
        self.button_cpu_views.setText(_translate("MainWindow", "BARS"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cpu_perc_plots), _translate("MainWindow", "CPU %"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cpu_per_bars), _translate("MainWindow", "CPU % Bars"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_extra_info), _translate("MainWindow", "Extra Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_memory_info), _translate("MainWindow", "Memory Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_net_info), _translate("MainWindow", "Networks Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_proc_info), _translate("MainWindow", "Processes Info"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.actionFIl.setText(_translate("MainWindow", "FIl"))


